---
# Homepage configuration
# See https://fontawesome.com/search for icons options

# Optional: Use external configuration file.
# Using this will ignore remaining config in this file
# externalConfig: https://example.com/server-luci/config.yaml

title: "Dashboard"
subtitle: "Ohara"
logo: "assets/homer-logo.png"
# Alternatively a fa icon can be provided:
# icon: "fas fa-skull-crossbones"

header: true # Set to false to hide the header
# Optional: Different hotkey for search, defaults to "/"
# hotkey:
#   search: "Shift"
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

columns: "3" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck: true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example).
                        # You should set it to true when using an authentication proxy, it also reloads the page when a redirection is detected when checking connectivity.

# Set the default layout and color scheme
defaults:
  layout: list # Either 'columns', or 'list'
  colorTheme: dark # One of 'auto', 'light', or 'dark'

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Ohara"
    icon: "fab fa-github"
    url: "https://github.com/thebrownbreadtoast/ohara"
    target: "_blank" # optional html tag target attribute
  - name: "dex-cli"
    icon: "fab fa-github"
    url: "https://github.com/thebrownbreadtoast/dex-cli"

# Services
# First level array represents a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Self-hosted containers"
    # A path to an image can also be provided. Note that icon take precedence if both icon and logo are set.
    logo: "https://github.com/NX211/homer-icons/blob/master/png/docker-moby.png?raw=true"
    # class: "highlight-purple" # Optional css class to add on the service group. 
    items:
      - name: "Jellyfin"
        # Alternatively a fa icon can be provided:
        logo: "https://raw.githubusercontent.com/NX211/homer-icons/7f15a0ec749f4604b9f18e5bd4ee955002d8c896/svg/jellyfin.svg"
        subtitle: "Jellyfin & Chill!"
        tag: "entertainment"
        url: "http://jellyfin.ohara.com"
        target: "_blank" # optional html tag target attribute
      - name: "Komga"
        # Alternatively a fa icon can be provided:
        logo: "https://github.com/NX211/homer-icons/blob/master/png/kavita.png?raw=true"
        subtitle: "Kaizoku ou ni ore wa naru!"
        tag: "entertainment"
        url: "http://komga.ohara.com"
        target: "_blank" # optional html tag target attribute
      - name: "copyparty"
        # Alternatively a fa icon can be provided:
        logo: "https://github.com/NX211/homer-icons/blob/master/png/filebrowser.png?raw=true"
        subtitle: "File Explorer"
        tag: "tools"
        url: "http://copyparty.ohara.com"
        target: "_blank" # optional html tag target attribute
      - name: "qBit"
        # Alternatively a fa icon can be provided:
        logo: "https://raw.githubusercontent.com/NX211/homer-icons/7f15a0ec749f4604b9f18e5bd4ee955002d8c896/svg/qbittorrent.svg"
        subtitle: "Illegal downloads happen here..."
        tag: "tools"
        url: "http://qbit.ohara.com"
        target: "_blank" # optional html tag target attribute
      - name: "2FAuth"
        # Alternatively a fa icon can be provided:
        logo: "https://github.com/NX211/homer-icons/blob/master/png/authelia.png?raw=true"
        subtitle: "Authenticator"
        tag: "tools"
        url: "http://2fa.ohara.com"
        target: "_blank" # optional html tag target attribute
      - name: "Pihole"
        # Alternatively a fa icon can be provided:
        logo: "https://github.com/NX211/homer-icons/blob/master/png/pi-hole.png?raw=true"
        subtitle: "DNS manager"
        tag: "tools"
        url: "http://pihole.ohara.com/admin"
        target: "_blank" # optional html tag target attribute
      - name: "OpenSpeedTest"
        # Alternatively a fa icon can be provided:
        logo: "https://github.com/NX211/homer-icons/blob/master/png/openspeedtest.png?raw=true"
        subtitle: "Check your connection with Ohara server"
        tag: "tools"
        url: "http://ost.ohara.com"
        target: "_blank" # optional html tag target attribute
