---
# Homepage configuration
# See https://fontawesome.com/search for icons options

# Optional: Use external configuration file.
# Using this will ignore remaining config in this file
# externalConfig: https://example.com/server-luci/config.yaml

title: "Dashboard"
subtitle: "Ohara"
logo: "assets/homer-logo.png"
# Alternatively a fa icon can be provided:
# icon: "fas fa-skull-crossbones"

header: true # Set to false to hide the header
# Optional: Different hotkey for search, defaults to "/"
# hotkey:
#   search: "Shift"
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

columns: "3" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck: true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example).
                        # You should set it to true when using an authentication proxy, it also reloads the page when a redirection is detected when checking connectivity.

# Set the default layout and color scheme
defaults:
  layout: list # Either 'columns', or 'list'
  colorTheme: dark # One of 'auto', 'light', or 'dark'

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Ohara"
    icon: "fab fa-github"
    url: "https://github.com/thebrownbreadtoast/ohara"
    target: "_blank" # optional html tag target attribute
  - name: "dex-cli"
    icon: "fab fa-github"
    url: "https://github.com/thebrownbreadtoast/dex-cli"
  - name: "Healthchecks.io"
    icon: "fas fa-heartbeat"
    url: "https://healthchecks.io/projects/6199303b-aca6-4c1d-aadc-c3cc95867adb/checks/"
    target: "_blank"
  - name: "Uptime Kuma Status"
    icon: "fas fa-tachometer-alt"
    url: "http://kuma.ohara.com/status/ohara"
    target: "_blank"

# Services
# First level array represents a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  # Entertainment
  - name: "Entertainment"
    logo: "https://raw.githubusercontent.com/NX211/homer-icons/7f15a0ec749f4604b9f18e5bd4ee955002d8c896/svg/jellyfin.svg"
    items:
      - name: "Jellyfin"
        logo: "https://raw.githubusercontent.com/NX211/homer-icons/7f15a0ec749f4604b9f18e5bd4ee955002d8c896/svg/jellyfin.svg"
        subtitle: "Jellyfin & Chill!"
        tag: "entertainment"
        url: "http://jellyfin.ohara.com"
        target: "_blank"
      - name: "Radarr"
        logo: "https://raw.githubusercontent.com/NX211/homer-icons/7f15a0ec749f4604b9f18e5bd4ee955002d8c896/png/radarr.png"
        subtitle: "Search movies here"
        tag: "entertainment"
        url: "http://radarr.ohara.com"
        target: "_blank"

  # Tools
  - name: "Tools"
    logo: "https://github.com/NX211/homer-icons/blob/master/png/docker-moby.png?raw=true"
    items:
      - name: "qBit"
        logo: "https://raw.githubusercontent.com/NX211/homer-icons/7f15a0ec749f4604b9f18e5bd4ee955002d8c896/svg/qbittorrent.svg"
        subtitle: "Torrent client"
        tag: "tools"
        url: "http://qbit.ohara.com"
        target: "_blank"
      - name: "copyparty"
        logo: "https://github.com/NX211/homer-icons/blob/master/png/filebrowser.png?raw=true"
        subtitle: "File Explorer"
        tag: "tools"
        url: "http://copyparty.ohara.com"
        target: "_blank"
      - name: "2FAuth"
        logo: "https://github.com/NX211/homer-icons/blob/master/png/authelia.png?raw=true"
        subtitle: "Authenticator"
        tag: "tools"
        url: "http://2fa.ohara.com"
        target: "_blank"

  # Monitoring & Dashboards
  - name: "Monitoring & Dashboards"
    logo: "https://github.com/NX211/homer-icons/blob/master/png/grafana.png?raw=true"
    items:
      - name: "Uptime Kuma"
        logo: "https://github.com/louislam/uptime-kuma/raw/master/public/icon.svg"
        subtitle: "Uptime & status monitoring"
        tag: "monitoring"
        url: "http://kuma.ohara.com"
        target: "_blank"

  # Networking
  - name: "Networking"
    logo: "https://github.com/NX211/homer-icons/blob/master/png/pi-hole.png?raw=true"
    items:
      - name: "Pihole"
        logo: "https://github.com/NX211/homer-icons/blob/master/png/pi-hole.png?raw=true"
        subtitle: "DNS manager"
        tag: "networking"
        url: "http://pihole.ohara.com/admin"
        target: "_blank"
      - name: "OpenSpeedTest"
        logo: "https://github.com/NX211/homer-icons/blob/master/png/openspeedtest.png?raw=true"
        subtitle: "Check your connection with Ohara server"
        tag: "networking"
        url: "http://ost.ohara.com"
        target: "_blank"
