services:
  qbit:
    image: linuxserver/qbittorrent:5.1.0-libtorrentv1
    container_name: qbit
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8081
    volumes:
      - ${QBIT_CONFIG_DIR:-/media/qbit/config}:/config
      - ${QBIT_DOWNLOAD_DIR:-/media/qbit}:/downloads
    ports:
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
