services:
  jellyfin:
    image: jellyfin/jellyfin:2025042805
    container_name: jellyfin
    env_file: ".env"
    user: "1000:1000"
    network_mode: 'host'
    volumes:
      - ${JELLYFIN_CONFIG_DIR:-/ohara/jellyfin/config}:/config:z
      - ${JELLYFIN_MEDIA_DIR:-/ohara/media}:/media:z
    restart: 'unless-stopped'
