services:
  homer:
    image: b4bz/homer:v25.04.1
    container_name: homer
    volumes:
      - ${HOMER_ASSETS_DIR:-/ohara/homer}:/www/assets
    ports:
      - 8080:8080
    user: 1000:1000
    environment:
      - INIT_ASSETS=1 # default, requires the config directory to be writable for the container user (see user option)
    restart: unless-stopped
