services:
  pihole:
    image: pihole/pihole:2025.07.1
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8888:80/tcp"
    environment:
      TZ: 'Asia/Kolkata'
      FTLCONF_webserver_api_password: 'superman'
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - '/ohara/pihole/etc-pihole:/etc/pihole'

    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:80/admin/"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
