services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: /ohara/komga/config
        target: /config
      - type: bind
        source: /ohara/komga/data
        target: /data
    ports:
      - 25600:25600
    user: "1000:1000"
    environment:
      - TZ=Asia/Kolkata
    restart: unless-stopped
