services:
  jellyfin:
    image: jellyfin/jellyfin:2025042805
    container_name: jellyfin
    env_file: ".env"
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - ${JELLYFIN_CONFIG_DIR:-/home/akshay/tools/ohara/configs/jellyfin}:/config
      - type: bind
        source: ${JELLYFIN_MEDIA_DIR:-/media/jellyfin}
        target: /media
    restart: 'unless-stopped'
