services:
  pihole:
    image: pihole/pihole:2025.07.1
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8888:80/tcp"
    environment:
      TZ: 'Asia/Kolkata'
      FTLCONF_webserver_api_password: 'superman'
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - '/ohara/pihole/etc-pihole:/etc/pihole'
    restart: unless-stopped
