services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /ohara/radarr/config:/config:z
      - ${JELLYFIN_MEDIA_DIR:-/ohara/media}:/data:z
    restart: unless-stopped
