services:
  jellyfin:
    image: jellyfin/jellyfin:2025042805
    container_name: jellyfin
    env_file: ".env"
    network_mode: 'host'
    volumes:
      - ${JELLYFIN_CONFIG_DIR:-/ohara/jellyfin/config}:/config:z
      - ${JELLYFIN_MEDIA_DIR:-/ohara/media}:/media:z

    restart: 'unless-stopped'
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8096/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
