services:
  prowlarr:
    image: linuxserver/prowlarr:2.0.5
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /ohara/prowlarr/config:/config:z
    ports:
      - 9696:9696
    restart: unless-stopped
