services:
  prowlarr:
    image: linuxserver/prowlarr:2.0.5
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /ohara/prowlarr/config:/config:z
    ports:
      - 9696:9696

    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:9696/"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
